# Generated by Django 3.2.6 on 2021-10-10 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0002_resetlinkdirectory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resetlinkdirectory',
            name='is_used',
        ),
        migrations.RemoveField(
            model_name='resetlinkdirectory',
            name='updated_at',
        ),
    ]
