# Generated by Django 3.2.7 on 2021-10-01 19:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('whitelist_mode', models.BooleanField(default=True, null=True)),
                ('whitelist_websites', models.JSONField(blank=True, default=dict, null=True)),
                ('variables', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_json', models.JSONField(blank=True, default=dict, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_responses', to='form_process.form')),
            ],
        ),
        migrations.CreateModel(
            name='FormAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('read', 'READ_ONLY'), ('write', 'WRITE'), ('admin', 'ADMIN')], default='read', max_length=50, null=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_accesses', to='form_process.form')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_accesses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
