# Generated by Django 3.2.7 on 2021-10-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='form',
            name='variables',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='whitelist_websites',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
