# Generated by Django 3.2.7 on 2021-10-03 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_process', '0002_auto_20211001_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
