# Generated by Django 3.2.7 on 2021-10-06 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_process', '0003_form_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='form',
            name='is_active',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
